### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by phiresky** [Zimmt/skeleton-generation#1]
the readme is missing a description and example outputs / inputs of what this is and what it does :P

**Comment by Zimmt** [comment]
Added a short introduction with example output.
Do you still think that something is missing?

**Comment by phiresky** [comment]
looks better:) imo it would be useful to add a description with more detail on how it works, what the input parameters are (e.g. random generation and generation based on a specific example) and what the output looks like (boxes or based on specific 3d models of bones). + a screenshot of the UI (which would already somewhat explain the parameters)
